Product.create(name: 'Coffee Beans', cost: 10)
Product.create(name: 'Coffee Cups', cost: 25)
Product.create(name: 'Cup Lids', cost: 15)
Product.create(name: 'Banana Bread', cost: 22)
Product.create(name: 'Straws', cost: 7.99)
Product.create(name: 'Oat Milk', cost: 18)
Product.create(name: 'Skim Milk', cost: 12)
Product.create(name: 'Almond Milk', cost: 23)
Product.create(name: 'Pumpkin Muffin', cost: 11.99)
Product.create(name: 'Yogurt', cost: 9.99)
Product.create(name: 'Pumpkin Muffin', cost: 11.99)
Product.create(name: 'Matcha Powder', cost: 29.99)
Product.create(name: 'Pumpkin Muffin', cost: 11.99)
Product.create(name: 'Sugar Packets', cost: 6.50)

# Order.create(name: 'Sugar Packets', cost: 6.50, quantity: 6)
# Order.create(name: 'Matcha Powder', cost: 29.99, quantity: 2)
# Order.create(name: 'Skim Milk', cost: 12, quantity: 3)


#  Cart.create(name: 'Sugar Packets', cost: 6.50, quantity: 6)
#  Cart.create(name: 'Matcha Powder', cost: 29.99, quantity: 2)
#  Cart.create(name: 'Skim Milk', cost: 12, quantity: 3)
# Cart.create(name: 'Pumpkin Muffin', cost: 11.99, quantity: 5)
